name: python-lint
on: # workflow triggers
  repository_dispatch:
    types:
      - mlflow_model_tag # payload event from webhook call
jobs:
  lint-code: # job name
    runs-on: ubuntu-latest
    steps:
      - name: black-linter
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
